vich_uploader:
    db_driver: orm

    mappings:
        publicacion_video:
            uri_prefix: /videos/publicaciones
            upload_destination: '%kernel.project_dir%/public/videos/publicaciones'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer